### ISSUE TITLE
Duplicate Class Attribute for Linkedin Button

### ISSUE THREAD

**Issue by singhnsk** [davidsneal/simplesharebuttons#10]
Hello

While using the simple buttons, the plugin outputs two class attributes for the linked-in share button. This causes page validation issues. All other buttons are well clean :)

Eg:
<a class="ssba_linkedin_share" class="ssba_share_link" href="http://www.linkedin.com/shareArticle?mini=true&amp;url=xyz

**Comment by davidsneal** [comment]
All sorted :) thanks!
