### ISSUE TITLE
Buttons on front page posts do not link to post content

### ISSUE THREAD

**Issue by TonyNYC** [davidsneal/simplesharebuttons#2]
Great plugin, love the lightweight simplicity of it.  Just awesome.

2 things I don't understand.  All my front page posts show the buttons, but they all link to the main site url instead of the content they are under.  Would be cool to be able to show the buttons on the front blog page but have them link to the actual post content.

Here is the URL:  www.multirotorusa.com
(The counter bubbles show main URL shares on the front page, rather than post shares)

For the Counter Settings I do have "Show only on posts and pages" checked off.  So the plugin is recognizing my home page not as the front page, but as any other page.

In Location Settings:  "Homepage" is unchecked and "Pages" "Posts" "Categories/Archives" are checked.

I think this is somehow due to the fact that I have a static page set for my home page.

**Comment by davidsneal** [comment]
Hi Tony,

This is undoubtedly linked to the fact you have a static page set for your homepage, although the page doesn't appear to be static as it contains your latest blog posts?

Could you please check if unchecking the 'pages' option removes them?

Seeing as your homepage seems to effectively be the standard WordPress-style homepage (a listing of blog posts and their excerpts) I would suggest having a try with having a try reverting to the standard format and giving that a try.

Thanks,

David

**Comment by TonyNYC** [comment]
I think it is probably the way the theme presents the home page.  They have a home page template, which I am not using.  I am using the standard wordpress static page option.  

When I uncheck pages, the share icons are no longer present on the front page: www.multirotorusa.com

I guess I will just do that and use [ssba] to include them on static pages other than the home page.  I may be able to put them in the home page header or side bar as well.  

Actually, just did it the opposite way.  I enabled pages and used [ssba_hide] on the static home page.  That makes it work great.  Thanks for the help.  I will definitely donate/tweet/fb for your plugin.

**Comment by TonyNYC** [comment]
Ahhhh, sorry... but I have another one for you.  The mailto link is doing some funny stuff:  http://www.multirotorusa.com/downloads/lemon-landing-gear/

It is probably just not playing nice with the file download plugin on that page.  I can remove the share buttons there, but maybe this will help you out in some way.
