### ISSUE TITLE
Typo / bug

### ISSUE THREAD

**Issue by cfsamet** [davidsneal/simplesharebuttons#5]
In the php file, there is this line of code:

```
                // share text with link
                $htmlShareButtons .= '<a href="http://www.simplesharebuttons.com" target="_blank" class="ssba_tooptip" id="ssba_tooptip""><span>www.simplesharebuttons.com</span>' . $arrSettings['ssba_share_text'];
```

There is an extra quotation here:   id="ssba_tooptip""

This causes some poor formatting on the page (when viewing the source), and not sure what else it might be breaking.

**Comment by davidsneal** [comment]
Thanks for pointing this out, it shall be fixed upon the release of version 3.5 :)
