### ISSUE TITLE
Losslessly Compress the Share Icons

### ISSUE THREAD

**Issue by singhnsk** [davidsneal/simplesharebuttons#8]
Hello David

This is an awesome plugin and because it is simple, it should keep up its simplicity. It would be great if you spend a few minute running your plugin's share icons through a loss-less compressing tool (File Optimizer works great) so that i can get a little reduced page size and maybe score better in the Google PageSpeed results.

I wouldn't have disturbed you, but i can't do that myself as you keep on updating the plugin :P

Thanks
![losseless pagespeed](https://cloud.githubusercontent.com/assets/5565338/2780266/5d9c221a-cb05-11e3-9890-e401492af3fd.png)

**Comment by davidsneal** [comment]
Hi,

Thanks for the suggestion, it shall be implemented for version 4.3 :+1: 

https://github.com/davidsneal/simplesharebuttons/tree/4.3/buttons

David
