### ISSUE TITLE
Activated plugin cases empty posts in WP 3.9

### ISSUE THREAD

**Issue by pixel-shock** [davidsneal/simplesharebuttons#9]
Hi,

first of all: THX for your work - nice plugin!
But your plugin causes empty blog pages, don't know why, but when I'm disabling your plugin, everything is ok - can you take a look at that pls? It's since your last update.

THX
Tino

**Comment by singhnsk** [comment]
You need to check your PHP Error log. Try disabling the counter on the share buttons. That solved the issue for me.

**Comment by davidsneal** [comment]
Please report back with errors if you can and I'll try and fix. It is likely related to having file_get_contents disabled. I may try and get all share counts working with cURL sometime.
